export function formatHelp(): string {
  return [
    "better-env",
    "",
    "Usage:",
    "  better-env init [--yes]",
    "  better-env pull [--environment <name>]",
    "  better-env dev [--environment <name>]",
    "  better-env run [--environment <name>] -- <command...>",
    "  better-env validate [--environment <name>]",
    "",
    "  better-env add <key> <value> [--environment <name>] [--sensitive]",
    "  better-env upsert <key> <value> [--environment <name>] [--sensitive]",
    "  better-env update <key> <value> [--environment <name>] [--sensitive]",
    "  better-env delete <key> [--environment <name>]",
    "",
    "  better-env load <file> [--environment <name>] [--mode add|update|upsert|replace] [--sensitive]",
    "    Aliases: --add | --update | --upsert | --replace (default: --upsert)",
    "",
    "  better-env environments list",
    "  better-env environments create <name>",
    "  better-env environments delete <name>",
    "    Alias: better-env envs list",
    "",
    "Config:",
    "  Place a `better-env.ts` in your project root that exports a config.",
    "",
    "Examples:",
    "  better-env init",
    "  better-env dev",
    "  better-env run -- bun run db:migrate",
    "  better-env upsert API_URL https://example.com --environment preview",
    "  better-env validate --environment development",
    "  better-env load .env.production --environment production --replace",
    "",
  ].join("\n");
}
